version: '3.9'
services:
  postgres:
    image: postgres:16.2
    container_name: postgres 
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
