# Generated by Django 4.2.11 on 2024-04-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_product_quantity'),
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='product_item',
        ),
        migrations.AddField(
            model_name='usercart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.product'),
            preserve_default=False,
        ),
    ]
