# Generated by Django 4.2.11 on 2024-04-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_product_discount_alter_product_slug'),
        ('carts', '0004_remove_usercart_product_usercart_product_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.productitem', verbose_name='product item & size'),
        ),
    ]
