# Generated by Django 4.2.11 on 2024-04-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='image',
        ),
    ]
