# Generated by Django 4.2.11 on 2024-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_style_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='slug',
        ),
        migrations.AddField(
            model_name='style',
            name='url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
