# Generated by Django 4.2.11 on 2024-04-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_style_slug_style_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
