# Generated by Django 4.2.11 on 2024-04-09 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_productshots_delete_productsize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productshots',
            options={'verbose_name_plural': 'Product shots'},
        ),
        migrations.AlterField(
            model_name='productshots',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.product'),
        ),
    ]
