# Generated by Django 4.2.11 on 2024-04-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_productshots_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='men', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
