# Generated by Django 4.2.11 on 2024-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_remove_product_gender_category_gender_delete_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/<django.db.models.fields.CharField>/'),
        ),
    ]
