# Generated by Django 4.2.11 on 2024-04-17 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_categorygender_alter_category_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='goods.categorygender'),
            preserve_default=False,
        ),
    ]
